### ISSUE TITLE
Don't compile with Swift 5.4

### ISSUE THREAD

**Issue by c0dedbear** [artrmz/ReadTimePublishPlugin#3]
Hello, I've updated to Publish 0.8.0 and Swift 5.4. This caused compile error of this plugin in my project.

```
.build/checkouts/ReadTimePublishPlugin/Sources/ReadTimePublishPlugin/ReadTimePublishPlugin.swift:32:64: error: 'byWords' is unavailable: Enumeration by words isn't supported in swift-corelibs-foundation
        strippedHTML.enumerateSubstrings(in: range, options: [.byWords, .substringNotRequired, .localized], { _, _, _, _ -> () in
                                                               ^~~~~~~
Foundation.NSString:18:27: note: 'byWords' has been explicitly marked unavailable here
        public static var byWords: NSString.EnumerationOptions
```

⚠️ Important notice: I use 'swift build' command at ubuntu18.04, seems from macOS and Xcode it's still compiling just fine.
